name: Deploy to Azure VM

on:
  push:
    branches: [main]

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # HTML Linting
      - name: Validate HTML files
        run: |
          npm install -g htmlhint
          htmlhint "**/*.html"

      # CSS (Tailwind) Linting
      - name: Lint Tailwind CSS with Stylelint
        run: |
          npm install stylelint stylelint-config-standard stylelint-config-tailwindcss --save-dev
          npx stylelint "**/*.css" --fix

      # JavaScript Linting
      - name: Validate JavaScript
        run: |
          npm install --save-dev @eslint/js globals
          npx eslint "assets/js/**/*.js"

  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest
    needs: validate 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker image
        run: |
          npm install
          npm run build
          docker build -t ghcr.io/fauzanwahyum/web-porto-docker:latest .
          docker push ghcr.io/fauzanwahyum/web-porto-docker:latest

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            set -e
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}
            docker stop web-porto-docker || true
            docker rm web-porto-docker || true
            docker pull ghcr.io/fauzanwahyum/web-porto-docker:latest
            docker run -d \
              --name web-porto-docker \
              -p 8080:80 \
              ghcr.io/fauzanwahyum/web-porto-docker:latest
            echo "✅ Deploy berhasil! Akses di: http://${{ secrets.AZURE_VM_IP }}:8080"
