name: Deploy to Azure VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install htmlhint untuk validasi HTML
      - name: Install htmlhint
        run: npm install -g htmlhint

      # Validasi HTML menggunakan htmlhint
      - name: Validate HTML files
        run: |
          # Contoh cek semua html di folder components, sesuaikan pathnya jika perlu
          htmlhint "**/*.html"
      
      # Validasi CSS (Tailwind + stylelint)
      - name: Validate CSS (Tailwind)
        run: |
          npm install -g tailwindcss stylelint stylelint-config-standard stylelint-config-tailwindcss
          npx tailwindcss -o output.css --minify
          npx stylelint "assets/css/**/*.css"

      # Validasi JavaScript
      - name: Validate JavaScript
        run: |
          npm install -g eslint
          npx eslint "assets/js/**/*.js"    
      
      # Login ke GHCR
      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build & push Docker image
      - name: Build and Push Docker image
        run: |
          npm install
          npm run build
          docker build -t ghcr.io/fauzanwahyum/web-porto-docker:latest .
          docker push ghcr.io/fauzanwahyum/web-porto-docker:latest

      # Deploy ke Azure VM
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            set -e
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}
            docker stop web-porto-docker || true
            docker rm web-porto-docker || true
            docker pull ghcr.io/fauzanwahyum/web-porto-docker:latest
            docker run -d \
              --name web-porto-docker \
              -p 8080:80 \
              ghcr.io/fauzanwahyum/web-porto-docker:latest

            echo "✅ Deploy berhasil! Akses di: http://${{ secrets.AZURE_VM_IP }}:8080"
