name: Deploy to Azure VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push
        run: |
          docker build -t ghcr.io/fauzanwahyum/web-porto-docker:latest .
          docker push ghcr.io/fauzanwahyum/web-porto-docker:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            docker stop web-porto-docker || true
            docker rm web-porto-docker || true
            docker pull ghcr.io/fauzanwahyum/web-porto-docker:latest
            docker run -d \
              --name web-porto-docker \
              -p 80:80 \
              ghcr.io/fauzanwahyum/web-porto-docker:latest
            
            echo "Deploy berhasil! Website running di http://$(curl -s ifconfig.me)"