name: Deploy to Azure VM

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build static files
        run: |
          mkdir -p dist
          cp -r *.html assets/ dist/

      - name: Build Docker image
        run: |
          LOWER_USERNAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t portfolio-web .
          docker tag portfolio-web ghcr.io/$LOWER_USERNAME/portfolio-web:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push to GHCR
        run: |
          LOWER_USERNAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$LOWER_USERNAME/portfolio-web:latest

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            echo "Deploying to /home/PortoFWM..."
            cd /home/PortoFWM
            
            # Pull image terbaru
            docker pull ghcr.io/${{ github.repository_owner }}/portfolio-web:latest
            
            # Hentikan dan hapus container lama jika ada
            docker stop portfolio || true
            docker rm portfolio || true
            
            # Jalankan container baru dengan volume binding
            docker run -d \
              --name portfolio \
              -p 80:80 \
              -v /home/PortoFWM/data:/usr/share/nginx/html \
              ghcr.io/${{ github.repository_owner }}/portfolio-web:latest
            
            echo "Deploy berhasil! Website running di http://$(curl -s ifconfig.me)"